// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxsgajphudfamvvejwwq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4c2dhanBodWRmYW12dmVqd3dxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMzU4MzMsImV4cCI6MjA1ODgxMTgzM30.b9-NbzLTYHIm7zUxL3f0sgQ5oo4VZrYq7qA5Y9I1jPU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);